"""empty message

Revision ID: 29a5d46007a1
Revises: 77e47d7cb6be
Create Date: 2022-09-19 16:46:34.479110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a5d46007a1'
down_revision = '77e47d7cb6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_election', sa.Column('state', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sn_election', 'state')
    # ### end Alembic commands ###
