"""empty message

Revision ID: 2a3ea18dc4fa
Revises: f65a024799e6
Create Date: 2022-06-26 16:22:56.662476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3ea18dc4fa'
down_revision = 'f65a024799e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sn_administrator', 'public_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=130),
               existing_nullable=False)
    op.alter_column('sn_superuser', 'public_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=130),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sn_superuser', 'public_id',
               existing_type=sa.String(length=130),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('sn_administrator', 'public_id',
               existing_type=sa.String(length=130),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
