"""empty message

Revision ID: 2bf95fc5046a
Revises: 58070265368d
Create Date: 2022-07-26 16:36:46.924053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf95fc5046a'
down_revision = '58070265368d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_office',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('route_name', sa.String(length=50), nullable=False),
    sa.Column('election_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'sn_administrator', ['id'])
    op.add_column('sn_candidate', sa.Column('programme', sa.String(length=100), nullable=False))
    op.add_column('sn_candidate', sa.Column('office_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'sn_candidate', ['id'])
    op.create_foreign_key(None, 'sn_candidate', 'sn_office', ['office_id'], ['id'])
    op.add_column('sn_election', sa.Column('route_name', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'sn_election', ['id'])
    op.create_unique_constraint(None, 'sn_election', ['route_name'])
    op.create_unique_constraint(None, 'sn_organization', ['id'])
    op.create_unique_constraint(None, 'sn_superuser', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sn_superuser', type_='unique')
    op.drop_constraint(None, 'sn_organization', type_='unique')
    op.drop_constraint(None, 'sn_election', type_='unique')
    op.drop_constraint(None, 'sn_election', type_='unique')
    op.drop_column('sn_election', 'route_name')
    op.drop_constraint(None, 'sn_candidate', type_='foreignkey')
    op.drop_constraint(None, 'sn_candidate', type_='unique')
    op.drop_column('sn_candidate', 'office_id')
    op.drop_column('sn_candidate', 'programme')
    op.drop_constraint(None, 'sn_administrator', type_='unique')
    op.drop_table('sn_office')
    # ### end Alembic commands ###
