"""empty message

Revision ID: 34e39528f320
Revises: 6153e3254d01
Create Date: 2022-07-29 21:08:26.562355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e39528f320'
down_revision = '6153e3254d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sn_voter_group_voter')
    op.drop_table('sn_voter_group_election')
    op.drop_table('sn_voter_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_voter_group_voter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('voter_group_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['voter_group_id'], ['sn_voter_group.id'], name='sn_voter_group_voter_voter_group_id_fkey'),
    sa.ForeignKeyConstraint(['voter_id'], ['sn_voter.id'], name='sn_voter_group_voter_voter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sn_voter_group_voter_pkey')
    )
    op.create_table('sn_voter_group_election',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voter_group_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('election_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], name='sn_voter_group_election_election_id_fkey'),
    sa.ForeignKeyConstraint(['voter_group_id'], ['sn_voter_group.id'], name='sn_voter_group_election_voter_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sn_voter_group_election_pkey')
    )
    op.create_table('sn_voter_group',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sn_organization.id'], name='sn_voter_group_organization_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sn_voter_group_pkey'),
    sa.UniqueConstraint('id', name='sn_voter_group_id_key')
    )
    # ### end Alembic commands ###
