"""empty message

Revision ID: 3c5a02b4e0f5
Revises: db0d00c85b65
Create Date: 2022-07-26 18:55:58.837055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5a02b4e0f5'
down_revision = 'db0d00c85b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_voter',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=130), nullable=False),
    sa.Column('telephone_number', sa.String(length=10), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sn_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('telephone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sn_voter_group',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sn_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sn_voter_group_election',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_group_id', sa.String(length=32), nullable=False),
    sa.Column('election_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], ),
    sa.ForeignKeyConstraint(['voter_group_id'], ['sn_voter_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sn_voter_group_voter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.String(length=32), nullable=False),
    sa.Column('voter_group_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['voter_group_id'], ['sn_voter_group.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['sn_voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sn_votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.String(length=32), nullable=False),
    sa.Column('election_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('office_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['sn_candidate.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['sn_office.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['sn_voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sn_votes')
    op.drop_table('sn_voter_group_voter')
    op.drop_table('sn_voter_group_election')
    op.drop_table('sn_voter_group')
    op.drop_table('sn_voter')
    # ### end Alembic commands ###
