"""empty message

Revision ID: 413053427fe1
Revises: 30292f13342a
Create Date: 2022-07-15 14:05:15.302862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413053427fe1'
down_revision = '30292f13342a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_organization', sa.Column('administrator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sn_organization', 'sn_administrator', ['administrator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sn_organization', type_='foreignkey')
    op.drop_column('sn_organization', 'administrator_id')
    # ### end Alembic commands ###
