"""empty message

Revision ID: 58070265368d
Revises: 
Create Date: 2022-07-23 03:15:37.077866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58070265368d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_administrator',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sn_superuser',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sn_organization',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('administrator_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['administrator_id'], ['sn_administrator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sn_election',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['sn_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sn_candidate',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('profile_image_url', sa.String(length=150), nullable=True),
    sa.Column('organization_id', sa.String(length=32), nullable=True),
    sa.Column('election_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['sn_organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sn_candidate')
    op.drop_table('sn_election')
    op.drop_table('sn_organization')
    op.drop_table('sn_superuser')
    op.drop_table('sn_administrator')
    # ### end Alembic commands ###
