"""empty message

Revision ID: a8b242917e19
Revises: 34e39528f320
Create Date: 2022-07-29 23:00:19.363814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b242917e19'
down_revision = '34e39528f320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_vote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.String(length=32), nullable=False),
    sa.Column('election_id', sa.String(length=32), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('office_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['sn_candidate.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['sn_office.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['sn_voter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sn_votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('voter_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('election_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('office_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['sn_candidate.id'], name='sn_votes_candidate_id_fkey'),
    sa.ForeignKeyConstraint(['election_id'], ['sn_election.id'], name='sn_votes_election_id_fkey'),
    sa.ForeignKeyConstraint(['office_id'], ['sn_office.id'], name='sn_votes_office_id_fkey'),
    sa.ForeignKeyConstraint(['voter_id'], ['sn_voter.id'], name='sn_votes_voter_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sn_votes_pkey')
    )
    op.drop_table('sn_vote')
    # ### end Alembic commands ###
