"""empty message

Revision ID: b4862d4e28ef
Revises: 3c5a02b4e0f5
Create Date: 2022-07-27 12:30:10.138671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4862d4e28ef'
down_revision = '3c5a02b4e0f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_election', sa.Column('type', sa.String(length=10), nullable=False))
    op.add_column('sn_election', sa.Column('college', sa.String(length=100), nullable=True))
    op.add_column('sn_election', sa.Column('programme', sa.String(length=10), nullable=True))
    op.add_column('sn_voter', sa.Column('student_id', sa.String(length=8), nullable=False))
    op.add_column('sn_voter', sa.Column('programme', sa.String(length=100), nullable=False))
    op.add_column('sn_voter', sa.Column('year', sa.String(length=6), nullable=False))
    op.create_unique_constraint(None, 'sn_voter', ['id'])
    op.create_unique_constraint(None, 'sn_voter_group', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sn_voter_group', type_='unique')
    op.drop_constraint(None, 'sn_voter', type_='unique')
    op.drop_column('sn_voter', 'year')
    op.drop_column('sn_voter', 'programme')
    op.drop_column('sn_voter', 'student_id')
    op.drop_column('sn_election', 'programme')
    op.drop_column('sn_election', 'college')
    op.drop_column('sn_election', 'type')
    # ### end Alembic commands ###
