"""empty message

Revision ID: c9c19525f4c2
Revises: 29a5d46007a1
Create Date: 2022-09-26 14:29:45.470896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c19525f4c2'
down_revision = '29a5d46007a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sn_election', 'route_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('sn_election_route_name_key', 'sn_election', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sn_election_route_name_key', 'sn_election', ['route_name'])
    op.alter_column('sn_election', 'route_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
