"""empty message

Revision ID: d11f60ba7a3a
Revises: a8b242917e19
Create Date: 2022-09-05 14:48:02.259458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11f60ba7a3a'
down_revision = 'a8b242917e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sn_election', 'programme',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=70),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sn_election', 'programme',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
