"""empty message

Revision ID: db0d00c85b65
Revises: 2bf95fc5046a
Create Date: 2022-07-26 17:14:00.446783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0d00c85b65'
down_revision = '2bf95fc5046a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_office', sa.Column('name', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sn_office', 'name')
    # ### end Alembic commands ###
