"""empty message

Revision ID: f65a024799e6
Revises: 6a793760a517
Create Date: 2022-06-26 09:35:29.600862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f65a024799e6'
down_revision = '6a793760a517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sn_superuser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=130), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_column('sn_administrator', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_administrator', sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_table('sn_superuser')
    # ### end Alembic commands ###
