"""empty message

Revision ID: f970ebe74ebc
Revises: 3d54e3c19f12
Create Date: 2022-07-18 17:21:06.881018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f970ebe74ebc'
down_revision = '3d54e3c19f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_election', sa.Column('organization_id', sa.String(length=32), nullable=True))
    op.drop_constraint('sn_election_organization_public_id_fkey', 'sn_election', type_='foreignkey')
    op.create_foreign_key(None, 'sn_election', 'sn_organization', ['organization_id'], ['public_id'])
    op.drop_column('sn_election', 'organization_public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sn_election', sa.Column('organization_public_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sn_election', type_='foreignkey')
    op.create_foreign_key('sn_election_organization_public_id_fkey', 'sn_election', 'sn_organization', ['organization_public_id'], ['public_id'])
    op.drop_column('sn_election', 'organization_id')
    # ### end Alembic commands ###
