name: CI Pipeline

on: 
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: [edited, opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m pip install --upgrade pip

    - name: Lint code
      run: |
        make lint
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: supernovae_test_db
          POSTGRES_PASSWORD: test_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m pip install --upgrade pip

      - name: Apply migrations to database
        run: make migrate
        env: 
          TEST_DATABASE_URL: 'postgresql://postgres:test_password@postgres:5432/supernovae_test_db'
      
      - name: Run tests
        run: make test_all
